# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatsnstats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toptrainingpartners',
            name='strava_id',
            field=models.IntegerField(default=0),
        ),
    ]
