# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatsnstats', '0004_auto_20170308_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.IntegerField(default=0)),
                ('user2', models.IntegerField(default=0)),
                ('ra_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='ttp_last_updated',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
