# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatsnstats', '0005_auto_20170314_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ttp_last_updated',
            field=models.DateTimeField(default='2017-03-15T05:05:25.518367'),
        ),
    ]
