# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatsnstats', '0007_auto_20170314_2215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopTrainingPartners',
        ),
        migrations.AddField(
            model_name='relationship',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='relationship',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
