# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatsnstats', '0008_auto_20170315_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('date', models.DateField(default='2000-01-01')),
                ('name', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='num_races',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='rs_last_updated',
            field=models.DateTimeField(default='2000-01-01T00:00:00Z'),
        ),
        migrations.AddField(
            model_name='users',
            name='total_distance',
            field=models.IntegerField(default=0),
        ),
    ]
