# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopTrainingPartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized', models.BooleanField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('partner1', models.CharField(max_length=100)),
                ('partner2', models.CharField(max_length=100)),
                ('partner3', models.CharField(max_length=100)),
                ('partner4', models.CharField(max_length=100)),
                ('partner5', models.CharField(max_length=100)),
                ('partner6', models.CharField(max_length=100)),
                ('partner7', models.CharField(max_length=100)),
                ('partner8', models.CharField(max_length=100)),
                ('partner9', models.CharField(max_length=100)),
                ('partner10', models.CharField(max_length=100)),
            ],
        ),
    ]
